#!/usr/bin/env python3
"""
🚀 Quick GitHub Pages Setup for SARB Reports
Automates the GitHub Pages deployment process
"""

import os
import subprocess
import json

def create_github_pages_deployment():
    """Create deployment package for GitHub Pages"""
    
    print("🚀 GITHUB PAGES DEPLOYMENT SETUP")
    print("=" * 50)
    
    # Create deployment package
    deployment_dir = "github_pages_deployment"
    os.makedirs(deployment_dir, exist_ok=True)
    
    # Copy all embeddable files
    import shutil
    embeddable_dir = "analysis/embeddable_reports"
    
    for file in os.listdir(embeddable_dir):
        if file.endswith('.html'):
            shutil.copy(
                os.path.join(embeddable_dir, file),
                os.path.join(deployment_dir, file)
            )
            print(f"📁 Copied: {file}")
    
    # Create README for GitHub
    readme_content = """# 🏛️ SARB Economic Reports

Live embeddable reports for Looker Studio integration.

## 📊 Available Reports

- [Executive Summary](./executive_summary_embed_embeddable.html)
- [Economic Alerts](./economic_alerts_embed_embeddable.html) 
- [Correlation Analysis](./sarb_correlation_analysis_embeddable.html)
- [Time Series Charts](./sarb_timeseries_chart_embeddable.html)

## 🔗 Looker Studio URLs

Use these URLs in Looker Studio "URL Embed" components:

```
https://YOUR-USERNAME.github.io/sarb-reports/executive_summary_embed_embeddable.html
https://YOUR-USERNAME.github.io/sarb-reports/economic_alerts_embed_embeddable.html
https://YOUR-USERNAME.github.io/sarb-reports/sarb_correlation_analysis_embeddable.html
https://YOUR-USERNAME.github.io/sarb-reports/sarb_timeseries_chart_embeddable.html
```

## 📅 Last Updated
""" + f"{os.popen('date /t').read().strip()} {os.popen('time /t').read().strip()}" + """

Generated by SARB Economic Pipeline
"""
    
    with open(os.path.join(deployment_dir, "README.md"), 'w') as f:
        f.write(readme_content)
    
    print("📄 Created README.md")
    
    # Create deployment instructions
    instructions = """
🚀 DEPLOYMENT INSTRUCTIONS
=========================

1. Create GitHub Repository:
   - Go to https://github.com/new
   - Repository name: sarb-reports
   - Make it PUBLIC
   - Click "Create repository"

2. Upload Files:
   - Upload all files from github_pages_deployment/ folder
   - You can drag & drop or use Git commands

3. Enable GitHub Pages:
   - Go to repository Settings
   - Scroll to "Pages" section
   - Source: "Deploy from a branch"
   - Branch: main
   - Folder: / (root)
   - Click Save

4. Get Your URLs:
   Replace YOUR-USERNAME with your GitHub username:
   
   Executive Summary:
   https://YOUR-USERNAME.github.io/sarb-reports/executive_summary_embed_embeddable.html
   
   Economic Alerts:
   https://YOUR-USERNAME.github.io/sarb-reports/economic_alerts_embed_embeddable.html
   
   Correlation Analysis:
   https://YOUR-USERNAME.github.io/sarb-reports/sarb_correlation_analysis_embeddable.html
   
   Time Series:
   https://YOUR-USERNAME.github.io/sarb-reports/sarb_timeseries_chart_embeddable.html

5. Use in Looker Studio:
   - Add Component → Embed
   - Select "URL Embed"
   - Paste the GitHub Pages URL
   - Adjust size and positioning

⏱️ GitHub Pages usually takes 5-10 minutes to deploy
🔄 Updates to files will automatically redeploy
"""
    
    with open("GITHUB_PAGES_DEPLOYMENT.txt", 'w') as f:
        f.write(instructions)
    
    print("📖 Created GITHUB_PAGES_DEPLOYMENT.txt")
    print(f"\n✅ Deployment package ready in: {deployment_dir}/")
    print("📖 See GITHUB_PAGES_DEPLOYMENT.txt for step-by-step instructions")

def main():
    create_github_pages_deployment()
    
    print("\n🎯 QUICK ALTERNATIVE: Netlify Drop")
    print("=" * 40)
    print("1. Go to https://www.netlify.com/")
    print("2. Drag github_pages_deployment/ folder to Netlify")
    print("3. Get instant URL like: https://amazing-name-123.netlify.app/")
    print("4. Use those URLs in Looker Studio")

if __name__ == "__main__":
    main()